apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: candidate-api-dev
resources:
  - ../../base
configMapGenerator:
  - name: candidate-api-config
    envs:
      - config.env
images:
  - name: candidateapi
    newName: ghcr.io/ericjbeauty/candidateapi
    newTag: dev
